/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SuperAgentEnvironment = {
    Default: "https://superme.leonsting.repl.co",
} as const;

export type SuperAgentEnvironment = typeof SuperAgentEnvironment.Default;
